### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by des-des**

### CODE REVIEW

**Comment by nelsonic** [comment]
@des-des even a micro-update to the readme is better than its current state...

**Comment by nelsonic** [comment]
@des-des do you mind if I merge this into Master just so there is _something_ in there...? :cake:

**Comment by des-des** [comment]
Sure thing.. sorry this fell by the wayside a bit. I can open up a second pull next week

**Comment by nelsonic** [comment]
You have a _lot_ on. :checkered_flag: 
And you're prioritising the important (_client-facing_) bits. :wink: 
Thanks for this great start! :+1:

**Pull request merged**
